#!/bin/bash
#  A shell script that extracts fields from an API JSON response
#  The script assumes the data.json file exists and it contains a valid json data

name=$(jq .name data.json)
formatted_height=$(jq .height data.json)
formatted_weight=$(jq .weight data.json)
type=$(jq .types[0].type.name data.json | sed 's/"//g' | awk '{ print toupper(substr($1, 1, 1)) tolower(substr($1, 2))}')
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."